Generalization: Make log file dirspec and prefix configurable
My userdata-backup script needs to log into its own var subdir and uses a backup- prefix there.

diff --git a/bin/borgmatic-create b/bin/borgmatic-create
--- a/bin/borgmatic-create
+++ b/bin/borgmatic-create
@@ -2,6 +2,8 @@
 set -o pipefail
 
 : ${BORGMATIC_CREATE_SOURCE_DIRSPEC=}
+: ${BORGMATIC_CREATE_LOG_DIRSPEC:="/var/log/${USER}/borgmatic"}
+: ${BORGMATIC_CREATE_LOG_PREFIX=}
 : ${BORGMATIC_CREATE_EXECUTIONMARKER_BASEDIR=}
 : ${BORGMATIC_SUBJECT=}
 : ${BORGMATIC_WHAT=}
@@ -59,8 +61,7 @@ if [ "$1" = --offer ]; then
 fi
 
 # Log the full verbose backup creation output into a timestamped log file.
-readonly LOG_DIRSPEC="/var/log/${USER}/borgmatic"
-[ -d "$LOG_DIRSPEC" ] || mkdir --parents -- "$LOG_DIRSPEC" || { printf >&2 'ERROR: Could not initialize log directory at %s\n' "$LOG_DIRSPEC"; exit 3; }
+[ -d "$BORGMATIC_CREATE_LOG_DIRSPEC" ] || mkdir --parents -- "$BORGMATIC_CREATE_LOG_DIRSPEC" || { printf >&2 'ERROR: Could not initialize log directory at %s\n' "$BORGMATIC_CREATE_LOG_DIRSPEC"; exit 3; }
 # Disable color output for logging and sampleLines.
 set -- --no-color "$@"
 
@@ -73,8 +74,9 @@ fi
 marker --update lastBackup
 
 # Enable output verbosity for backup creation to list each backed up file.
+logFilePrefix="${BORGMATIC_CREATE_LOG_PREFIX:-$BORGMATIC_SUBJECT}"
 if borgmatic create --verbosity 1 --files "$@" \
-    | borgmatic-creationLogger "${LOG_DIRSPEC}/${BORGMATIC_SUBJECT}${BORGMATIC_SUBJECT:+-}"
+    | borgmatic-creationLogger "${BORGMATIC_CREATE_LOG_DIRSPEC}/${logFilePrefix}${logFilePrefix:+-}"
 then
     marker --update lastGoodBackup --increment-context
 
