userdata-backup: Usability: Improve passphrase message
I didn't immediately know what this is / where to get it from.

diff --git a/bin/userdata-backup b/bin/userdata-backup
--- a/bin/userdata-backup
+++ b/bin/userdata-backup
@@ -57,7 +57,7 @@ if [ ! -e "$borgmaticExcludesFilespec" ]; then
 fi
 
 if [ ! -r "$borgmaticPassphraseFilespec" ]; then
-    printf >&2 'ERROR: No borgmatic passphrase set yet. Write to %s\n' "$borgmaticPassphraseFilespec"
+    printf >&2 'ERROR: No borgmatic passphrase set yet. Create a good encryption phrase and write to %s\n' "$borgmaticPassphraseFilespec"
     exit 2
 fi
 
